server:
  port: 4949
spring:
  datasource:
    url: jdbc:mysql://43.155.176.239:3306/dessert
    username: dessert
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  security:
    user:
      name: 'admin'
      password: '123456'
      roles:
        - admin
        - user